name: Go

on:
  push:
    branches: [ main ]

jobs:
  test-on-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Get Go version from go.mod
      run: |
        go_version=$(cat go.mod | grep "^go" | cut -d ' ' -f 2)
        echo "go_version=${go_version}" >> $GITHUB_ENV

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ env.go_version }}

    - name: Fmt
      run: |
        files=$(gofmt -l . | grep -v vendor || true)
        if [[ -n "$files" ]]; then
          echo "failed gofmt for the following: $files"
          exit 1
        fi

    - name: Vet
      run: go vet ./...

    - name: Install Ginkgo
      run: go install github.com/onsi/ginkgo/v2/ginkgo

    - name: Test
      run: ginkgo --keep-going --trace -r --fail-on-pending --randomize-all --nodes=7 --race --timeout 20m ./...

  test-on-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ env.go_version }}

    - name: Vet
      run: go vet ./...

    - name: Install Ginkgo
      run: go install github.com/onsi/ginkgo/v2/ginkgo

    - name: Test
      run: ginkgo --keep-going --trace -r --fail-on-pending --randomize-all --nodes=7 --race --timeout 20m ./...
